#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

bspc rule -a "TelegramDesktop" desktop=^4
bspc rule -a "Zathura" state=tiled
bspc rule -a "Emacs" state=tiled

