#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true
bspc config top_padding         16

# bspc config focused_border_color "#398277"

#bspc config top_monocle_padding 100
#bspc config bottom_monocle_padding 100
#bspc config left_monocle_padding 300
#bspc config right_monocle_padding 300

bspc rule -a "TelegramDesktop" desktop=^4
bspc rule -a "Zathura" state=tiled
bspc rule -a "LibreOffice" state=tiled

$HOME/.config/polybar/launch.sh &
