#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true
bspc config top_padding         16

# bspc config focused_border_color "#398277"

$HOME/.config/polybar/launch.sh &
