#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Provide source and target directories."
    exit 1
fi

if [ ! -d "$1" ]; then
    echo "No source directory."
    exit 1
fi

if [ ! -d "$2" ]; then
    echo "No target directory."
    exit 1
fi

while true; do
    inotifywait -r -e modify,create,delete,move "$1"
    rsync -avz --delete "$1" "$2"
done

