#!/bin/sh

HOST=192.168.1.103
PORT=9889
TIMEOUT=0.5

TEXT=$(timeout "$TIMEOUT" nc -d "$HOST" "$PORT")

if [ -z "$TEXT" ]; then
  exit
fi

if [ "$1" == "--notify" ]; then
  notify-send -t 5000 -u normal "Последнее сообщение" "$TEXT"
else
  sleep 0.3
  echo "$TEXT" | grep -o -E '[0-9]+' | head -1 | xdotool type --file -
fi
