#!/bin/sh

SERVER_URL="https://otp.suive.name"
USERNAME=admin
PASSWORD=$(pass otphelper)
TIMEOUT=0.5

TEXT=$(timeout "$TIMEOUT" curl -s -u "$USERNAME:$PASSWORD" "$SERVER_URL/otp" -H "Accept: text/plain")

if [ -z "$TEXT" ]; then
  exit
fi

if [ "$1" == "--notify" ]; then
  notify-send -t 5000 -u normal "Последнее сообщение" "$TEXT"
else
  sleep 0.3
  echo "$TEXT" | xdotool type --file -
fi
