#!/bin/sh

# Prompts user to select and uninstall package(s) using AUR wrapper.
PACKAGE=$(yay -Pc | fzf -m --preview 'yay -Si {1}' | cut -f1 -) # Separate variable to allow confirming.
yay -S "$PACKAGE" 
