#!/bin/bash
# vi: ft=bash

set -u
set -e
set -o pipefail

# Display services and choose one with Rofi.
items="💤 Sleep\n🌀 Hibernate\n🎮 Reboot to Windows\n🔄 Reboot\n⏹️ Poweroff"

# Choose an action.
action=$(echo -e $items | rofi -dmenu -p "select action" -matching fuzzy | cut -d' ' -f2)

case $action in
    Sleep)
        systemctl suspend
        ;;
    Hibernate)
        systemctl hibernate
        ;;
    Reboot to Windows)
        sudo reboot-to-windows
        ;;
    Reboot)
        reboot
        ;;
    Poweroff)
        poweroff
        ;;
esac

